zzeldas/wechairaboutyou

package.json, server/db/models/chairs.js, server/db/models/order.js, server/db/models/orderdetail.js
=> models, all chairs, order details, order

server/db/models/user.js
=> User model updated

client/components/AllUsers.js, client/store/user.js, script/seed.js, server/api/users.js, server/api/users.spec.js, server/db/models/user.js, server/db/models/user.spec.js
=> All users routes

server/api/users.js, server/auth/index.js, server/db/models/user.js, server/middleware.js
code review 1 fixes for user model
=> Fix user model

client/store/combineReducers.js, client/store/index.js, client/store/singleUser.js, client/store/singleUser.spec.js, client/store/users.js, client/store/users.spec.js
=> Users reducer

script/seed.js, server/api/cart.js, server/api/index.js, server/db/models/cart.js, server/db/models/cartproduct.js, server/db/models/index.js, server/db/models/order.js, server/db/models/orderproduct.js, server/db/models/orderproduct.spec.js
=> Fix order models

client/store/combineReducers.js, client/store/products.js, client/store/products.spec.js, client/store/singleProduct.js, client/store/singleProduct.spec.js, script/seed.js, server/api/users.spec.js, server/db/models/user.spec.js
=> All products reducer

client/components/navbar.js, public/index.html, script/seed.js, server/api/products.js, server/db/models/category.js, server/db/models/index.js, server/db/models/product.js
=> Fix product model

client/components/AllProducts.js, client/components/AllUsers.js, client/components/Home.js, client/components/auth-form.js, client/components/navbar.js, client/index.js, client/routes.js, client/store/index.js, client/store/products.js, server/api/users.spec.js, server/auth/index.js, server/db/models/product.js
=> products components

client/components/AllProducts.js, client/components/SingleProduct.js, client/components/auth-form.js, client/components/navbar.js, client/routes.js, client/store/singleUser.js, client/store/users.js, server/api/users.js, server/auth/index.js
=> Product components continue

client/components/AllUsers.js, client/store/index.js, client/store/users.js, server/api/users.js
=> Users comp

client/components/AllProducts.js, client/components/AllUsers.js, client/components/SingleProduct.js, client/components/updateProduct.js, client/routes.js, server/api/index.js
=> cart route fixed

.travis.yml, server/api/products.js
=> travis changed

client/components/Cart.js
=> fix branch

server/api/carts.js, server/db/models/product.js
=> create cart route to change status from pending to completed

client/components/navbar.js, public/index.html
=> Set bundle

client/components/AllProducts.js, client/components/Cart.js, client/components/navbar.js, client/store/cart.js, public/index.html
=> fixed bugs

client/components/navbar.js
=> removed nav link

client/components/AllProducts.js, client/components/Cart.js, client/components/Home.js, client/components/navbar.js, client/store/cart.js, client/store/products.spec.js, client/store/singleProduct.spec.js, client/store/singleUser.spec.js, client/store/users.spec.js, public/index.html, public/style.css, script/seed.js, server/api/carts.js, server/api/products.spec.js, server/api/users.spec.js, server/db/models/orderproduct.spec.js, server/db/models/product.js, server/db/models/products.spec.js
=> Debug heroku

client/components/ProductForm.js, client/components/newProduct.js, client/components/removeProduct.js, client/components/removeProductForm.js, client/components/updateProduct.js, public/style.css, server/api/products.js
=> Code review2 changes

client/components/Profile.js, client/components/SingleProduct.js, client/components/navbar.js, client/routes.js, public/style.css, script/seed.js, server/api/carts.js, server/api/users.js, server/auth/index.js, server/middleware.js
=> User profile comp

client/components/Cart.js, client/components/CheckoutPage.js, client/components/ConfirmationPage.js, client/store/checkout.js, client/store/confirmationpage.js
=> Debug check confirm

script/seed.js
=> added gaming chair data

client/components/Cart.js, client/components/Profile.js
=> rendering text for order history
